// <auto-generated />
namespace MyMVCApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "201908060751404_DB_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
